-- GangWarsRP - Job Definitions
-- All jobs are defined here and loaded by the jobs module

GWRP.Jobs = GWRP.Jobs or {}
GWRP.Jobs.List = {
    -- Legal Jobs
    citizen = {
        name = "Citizen",
        description = "A regular citizen of the city",
        category = GWRP.JOB_CATEGORY.LEGAL,
        salary = 50,
        maxSlots = 0, -- unlimited
        weapons = {},
        model = "models/player/group01/male_01.mdl",
    },
    police = {
        name = "Police Officer",
        description = "Protect and serve the city",
        category = GWRP.JOB_CATEGORY.LEGAL,
        salary = 150,
        maxSlots = 4,
        weapons = {"weapon_pistol", "weapon_stunstick"},
        model = "models/player/police.mdl",
    },
    police_chief = {
        name = "Police Chief",
        description = "Lead the police force",
        category = GWRP.JOB_CATEGORY.LEGAL,
        salary = 200,
        maxSlots = 1,
        weapons = {"weapon_pistol", "weapon_stunstick", "weapon_smg1"},
        model = "models/player/police.mdl",
    },
    mayor = {
        name = "Mayor",
        description = "Run the city, set laws, call lockdowns",
        category = GWRP.JOB_CATEGORY.LEGAL,
        salary = 250,
        maxSlots = 1,
        weapons = {},
        model = "models/player/breen.mdl",
    },
    medic = {
        name = "Medic",
        description = "Heal citizens for money",
        category = GWRP.JOB_CATEGORY.LEGAL,
        salary = 100,
        maxSlots = 3,
        weapons = {},
        model = "models/player/kleiner.mdl",
    },
    gun_dealer = {
        name = "Gun Dealer",
        description = "Sell weapons to citizens",
        category = GWRP.JOB_CATEGORY.LEGAL,
        salary = 75,
        maxSlots = 2,
        weapons = {},
        model = "models/player/monk.mdl",
    },
    car_dealer = {
        name = "Car Dealer",
        description = "Sell vehicles to citizens",
        category = GWRP.JOB_CATEGORY.LEGAL,
        salary = 75,
        maxSlots = 2,
        weapons = {},
        model = "models/player/magnusson.mdl",
    },

    -- Illegal Jobs
    gang_member = {
        name = "Gang Member",
        description = "Represent your gang on the streets",
        category = GWRP.JOB_CATEGORY.ILLEGAL,
        salary = 45,
        maxSlots = 0,
        weapons = {},
        requiresGang = true,
        model = "models/player/group03/male_01.mdl",
    },
    gang_leader = {
        name = "Gang Leader",
        description = "Lead your gang to dominance",
        category = GWRP.JOB_CATEGORY.ILLEGAL,
        salary = 60,
        maxSlots = 0,
        weapons = {},
        requiresGang = true,
        requiresGangLeader = true,
        model = "models/player/group03/male_04.mdl",
    },
    hitman = {
        name = "Hitman",
        description = "Accept contracts to eliminate targets",
        category = GWRP.JOB_CATEGORY.ILLEGAL,
        salary = 0,
        maxSlots = 2,
        weapons = {"weapon_pistol"},
        model = "models/player/leet.mdl",
    },
    drug_dealer = {
        name = "Drug Dealer",
        description = "Cook and sell drugs for profit",
        category = GWRP.JOB_CATEGORY.ILLEGAL,
        salary = 30,
        maxSlots = 3,
        weapons = {},
        model = "models/player/group03/male_02.mdl",
    },
    thief = {
        name = "Thief",
        description = "Pick locks and steal valuables",
        category = GWRP.JOB_CATEGORY.ILLEGAL,
        salary = 25,
        maxSlots = 4,
        weapons = {},
        model = "models/player/arctic.mdl",
    },
    arms_dealer = {
        name = "Arms Dealer",
        description = "Deal in illegal weapons on the black market",
        category = GWRP.JOB_CATEGORY.ILLEGAL,
        salary = 40,
        maxSlots = 2,
        weapons = {},
        model = "models/player/guerilla.mdl",
    },
}
